export const FETCH_INITIAL_COMPETANCY_SUCESS =
  "FETCH_INITIAL_COMPETANCY_SUCESS";
export const FETCH_INITIAL_COMPETANCY_FAILURE =
  "FETCH_INITIAL_COMPETANCY_FAILURE";
export const UPDATE_COMPETANCY_WEIGHT = "UPDATE_COMPETANCY_WEIGHT";

export const SAVE_COMPETANCY_SUCESS = "SAVE_COMPETANCY_SUCESS";
export const SAVE_COMPETANCY_FAILURE = "SAVE_COMPETANCY_FAILURE";
export const SAVE_COMPETANCY_EMPTY= "SAVE_COMPETANCY_EMPTY";


export const LOADING_COMPETANCY = "LOADING_COMPETANCY";
