
export const FETCH_PERSONALDEV_COMP_SUCCESS = "FETCH_PERSONALDEV_COMP_SUCCESS";
export const FETCH_PERSONALDEV_COMP_FAILURE = "FETCH_PERSONALDEV_COMP_FAILURE";


export const GET_PERSONALDEV_COMP_LOADING = "GET_PERSONALDEV_COMP_LOADING";
export const GET_PERSONALDEV_COMP_SUCCESS = "GET_PERSONALDEV_COMP_SUCCESS";
export const GET_PERSONALDEV_COMP_FAILURE = "GET_PERSONALDEV_COMP_FAILURE";
