export const SEARCH_PLAYER_EMAIL = 'SEARCH_PLAYER_EMAIL';
export const SEARCH_PLAYER_EMAIL_SUCCESS = 'SEARCH_PLAYER_EMAIL_SUCCESS';
export const SEARCH_PLAYER_EMAIL_FAILURE = 'SEARCH_PLAYER_EMAIL_FAILURE';

export const SELECTED_PLAYER_LINK = 'SELECTED_PLAYER_LINK';
export const SELECTED_PLAYER_LINK_SUCCESS = 'SELECTED_PLAYER_LINK_SUCCESS';
export const SELECTED_PLAYER_LINK_FAILURE = 'SELECTED_PLAYER_LINK_FAILURE';

export const FETCH_PLAYER_EMAIL_LIST = 'FETCH_PLAYER_EMAIL_LIST';
export const FETCH_PLAYER_EMAIL_LIST_SUCCESS = 'FETCH_PLAYER_EMAIL_LIST_SUCCESS';
export const FETCH_PLAYER_EMAIL_LIST_FAILURE = 'FETCH_PLAYER_EMAIL_LIST_FAILURE';
