export const FETCH_VIDEO_ANALYSIS_REQUEST = 'FETCH_VIDEO_ANALYSIS_REQUEST';
export const FETCH_VIDEO_ANALYSIS_SUCCESS = 'FETCH_VIDEO_ANALYSIS_SUCCESS';
export const FETCH_VIDEO_ANALYSIS_FAILURE = 'FETCH_VIDEO_ANALYSIS_FAILURE';

export const SELECT_VIDEO_FOR_ANALYSIS = 'SELECT_VIDEO_FOR_ANALYSIS';
export const FETCH_VIDEO_REQUEST = 'FETCH_VIDEO_REQUEST';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_FAILURE = 'FETCH_VIDEO_FAILURE';


export const FETCH_VIDEO_COMPARE_SUCESS = 'FETCH_VIDEO_COMPARE_SUCESS';
export const FETCH_VIDEO_COMPARE_FAILURE = 'FETCH_VIDEO_COMPARE_FAILURE';

