export const FETCH_BOARD_REQUEST = 'FETCH_BOARD_REQUEST';
export const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
export const FETCH_BOARD_FAILURE = 'FETCH_BOARD_FAILURE';


export const POST_BOARD_REQUEST = 'POST_BOARD_REQUEST';
export const POST_BOARD_SUCCESS = 'POST_BOARD_SUCCESS';
export const POST_BOARD_FAILURE = 'POST_BOARD_FAILURE';


export const FETCH_ALLBOARD_REQUEST = 'FETCH_ALLBOARD_REQUEST';
export const FETCH_ALLBOARD_SUCCESS = 'FETCH_ALLBOARD_SUCCESS';
export const FETCH_ALLBOARD_FAILURE = 'FETCH_ALLBOARD_FAILURE';

export const FETCH_SINGLEBOARD_REQUEST = 'FETCH_SINGLEBOARD_REQUEST';
export const FETCH_SINGLEBOARD_SUCCESS = 'FETCH_SINGLEBOARD_SUCCESS';
export const FETCH_SINGLEBOARD_FAILURE = 'FETCH_SINGLEBOARD_FAILURE';