export const FETCH_COMPETANCY_AGGREGATION = 'FETCH_COMPETANCY_AGGREGATION';
export const FETCH_COMPETANCY_AGGREGATION_SUCCESS = 'FETCH_COMPETANCY_AGGREGATION_SUCCESS';
export const FETCH_COMPETANCY_AGGREGATION_FAILURE = 'FETCH_COMPETANCY_AGGREGATION_FAILURE';
